name: HySpecNet-11k
title: A Large-Scale Hyperspectral Benchmark Dataset
email: m.fuchs@tu-berlin.de

menu:
  - title: About
    link: "#about-hyspecnet-11k"
  - title: Downloads
    link: "#downloads"
  - title: FAQ
    link: "#faq"
  - title: License
    link: "#license"
  - title: Contact
    link: "#contact"
